# Example docker-compose.yml for development and production structure
version: '3.8'

# Define your services here, e.g.:
# services:
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: commodity_db
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#   web:
#     build: .
#     command: gunicorn commodity_tracker.wsgi:application --bind 0.0.0.0:8000 --workers 3
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       - DJANGO_SETTINGS_MODULE=commodity_tracker.settings.production
# volumes:
#   postgres_data: 